name: division
description: Simple to use yet powerful style widgets with syntax inspired by CSS.
version: 0.10.0

homepage: https://github.com/ReinBentdal/division
repository: https://github.com/ReinBentdal/division

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
